"use strict";
(async()=>{
 const iframe=document.getElementById("pagina"),relatorio=document.getElementById("relatorio"),logs=[];
 const esperar=ms=>new Promise(r=>setTimeout(r,ms));
 const afirmar=(ok,msg)=>{if(!ok)throw new Error(msg);logs.push("OK: "+msg);};
 try{
  await new Promise(r=>{if(iframe.contentDocument.getElementById("base") && iframe.contentDocument.readyState==="complete")r();else iframe.onload=r;});
  const w=iframe.contentWindow,d=w.document,$=id=>d.getElementById(id);
  const quadro=()=>new Promise(r=>w.setTimeout(r,60));
  const ate=async(fn)=>{for(let i=0;i<100;i++){if(fn())return;await quadro();await esperar(40);}throw new Error("Espera excedida: "+$("estado").textContent);};
  async function arquivo(nome,pintar){const c=document.createElement("canvas");c.width=200;c.height=150;pintar(c.getContext("2d"));return new File([await new Promise(r=>c.toBlob(r))],nome,{type:"image/png"});}
  function inserir(id,file){const dt=new w.DataTransfer();dt.items.add(file);$(id).files=dt.files;$(id).dispatchEvent(new w.Event("change"));}
  const base=await arquivo("base-sintetica.png",c=>{c.fillStyle="#14283c";c.fillRect(0,0,200,150);c.fillStyle="#b4c8dc";c.fillRect(0,0,200,18);});
  const hycosy=await arquivo("hycosy-sintetica.png",c=>{c.fillStyle="black";c.fillRect(0,0,200,150);c.fillStyle="#f05030";c.fillRect(55,35,80,70);c.fillStyle="#ffb090";c.fillRect(115,90,10,10);c.fillStyle="black";c.fillRect(75,55,12,15);c.fillStyle="white";c.fillRect(0,0,200,12);c.fillRect(188,138,10,10);});
  inserir("base",base);inserir("hycosy",hycosy);await ate(()=>!$("baixar").disabled);
  const canvas=$("resultado"),ctx=canvas.getContext("2d");
  const pixels=()=>ctx.getImageData(0,0,200,150).data;
  const pixel=(x,y)=>Array.from(ctx.getImageData(x,y,1,1).data);
  const ajustar=async(id,v)=>{
    if(id==="opacidade"){id="transparencia";v=100-v;}
    if(id==="x" || id==="y"){
      const r=canvas.getBoundingClientRect(),delta=(v-Number($(id).value))/100;
      const inicio=delta<0?.8:.2;
      canvas.setPointerCapture=()=>{};
      const emitir=(tipo,fator)=>canvas.dispatchEvent(new w.PointerEvent(tipo,{pointerId:7,button:0,clientX:r.left+r.width*(id==="x"?fator:.5),clientY:r.top+r.height*(id==="y"?fator:.5)}));
      emitir("pointerdown",inicio);emitir("pointermove",inicio+delta);emitir("pointerup",inicio+delta);
    }else{$(id).value=v;$(id).dispatchEvent(new w.Event("input"));}
    await quadro();
  };
  afirmar(!d.querySelector('input[type="range"]#x,input[type="range"]#y'),"Posição não aparece como controle na barra");
  afirmar(canvas.width===200 && canvas.height===150,"Dimensões originais da base preservadas");
  afirmar(pixel(0,0).join() === "180,200,220,255","Cabeçalho intacto");
  afirmar(pixel(0,80).join() === "20,40,60,255","Fundo fora da sobreposição intacto");
  afirmar(pixel(100,80)[0]>20,"Sobreposição visível");
  const visivelInicial=pixels().slice();
  await ajustar("transparencia",100);
  afirmar(pixel(100,80).join()==="20,40,60,255","Transparência 100% oculta a Hycosy");
  await ajustar("transparencia",15);
  afirmar(pixels().every((n,i)=>n===visivelInicial[i]),"Transparência pode ser restaurada sem alterar cores ou posição");
  const limites=()=>{
    const dados=pixels();let x0=200,y0=150,x1=-1,y1=-1;
    for(let y=18;y<150;y++)for(let x=0;x<200;x++){
      const i=(y*200+x)*4;
      if(Math.abs(dados[i]-20)+Math.abs(dados[i+1]-40)+Math.abs(dados[i+2]-60)>8){x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y);}
    }
    return {w:x1-x0+1,h:y1-y0+1};
  };
  const proporcaoOriginal=limites();await ajustar("largura",150);const maisLarga=limites();
  afirmar(maisLarga.w>proporcaoOriginal.w*1.4 && Math.abs(maisLarga.h-proporcaoOriginal.h)<=2,"Largura aumenta somente a dimensão horizontal");
  await ajustar("largura",100);await ajustar("altura",60);const achatada=limites();
  afirmar(achatada.h<proporcaoOriginal.h*.7 && Math.abs(achatada.w-proporcaoOriginal.w)<=2,"Altura reduz somente a dimensão vertical");
  await ajustar("altura",100);
  const modo=async v=>{$("modo-fusao").value=v;$("modo-fusao").dispatchEvent(new w.Event("change"));await quadro();};
  afirmar($("preservar-relevo").checked,"Preservação do relevo começa ativada");
  await modo("source-over");await ajustar("opacidade",100);await ajustar("brilho",300);
  const detalhePreservado=pixel(115,98),meioTom=pixel(100,80);
  afirmar(detalhePreservado[1]>meioTom[1] && detalhePreservado[1]<255,"Luminosidade alta mantém gradações sem estourar o canal de luz");
  $("preservar-relevo").checked=false;$("preservar-relevo").dispatchEvent(new w.Event("change"));await quadro();
  afirmar(pixel(115,98)[1]===255,"Comparação confirma saturação do ajuste anterior");
  $("preservar-relevo").checked=true;$("preservar-relevo").dispatchEvent(new w.Event("change"));await quadro();
  afirmar(pixel(115,98).join()===detalhePreservado.join(),"Reativar preservação recupera a gradação de luz original processada");
  await ajustar("brilho",100);await ajustar("opacidade",100);await modo("source-over");
  const opaca=pixel(100,80);
  await modo("screen");
  afirmar(pixel(100,80).join()===opaca.join() && opaca.join()==="240,80,48,255","Transparência zero mostra pixels da Hycosy sem mistura com o 3D");
  const baseAlternativa=await arquivo("base-alternativa.png",c=>{c.fillStyle="#f0d080";c.fillRect(0,0,200,150);});
  inserir("base",baseAlternativa);await ate(()=>!$("baixar").disabled);await quadro();
  afirmar(pixel(100,80).join()===opaca.join(),"Hycosy opaca independe da cor da base por baixo");
  inserir("base",base);await ate(()=>!$("baixar").disabled);await quadro();
  await ajustar("opacidade",70);await modo("source-over");
  const normal=pixel(100,80);
  await modo("screen");const clara=pixel(100,80);
  afirmar(clara.slice(0,3).every((n,i)=>n>=normal[i]) && clara[1]>normal[1],"Fusão clara ilumina a camada em comparação ao modo anterior");
  afirmar(Math.abs(clara[1]-(40*.3+(255-(255-40)*(255-80)/255)*.7))<=2,"Mistura clara segue a combinação de luminosidade esperada");
  afirmar(pixel(0,80).join()==="20,40,60,255","Fusão clara não altera regiões fora da camada");
  await ajustar("opacidade",100);
  const pBuraco=pixel(78,73);afirmar(pBuraco[0]===20 && pBuraco[1]===40,"Fundo preto interno fica transparente");
  const anterior=pixels().slice();await ajustar("rx",35);await ajustar("ry",-30);await ajustar("giro",20);
  afirmar(pixels().some((n,i)=>n!==anterior[i]),"Perspectivas e rotação alteram a projeção");
  await ajustar("y",0);
  afirmar(Math.abs(Number($("y").value))<.01,"Arrastar a imagem modifica a posição vertical");
  const cabecalho=ctx.getImageData(0,0,200,18).data;
  afirmar(cabecalho.every((n,i)=>n===[180,200,220,255][i%4]),"Cabeçalho protegido mesmo com a camada movida por cima");
  $("repor").click();await quadro();
  afirmar($("colorir").value==="0","Cor original da Hycosy mantida antes da escolha");
  await ajustar("cor","#000000");
  afirmar($("modo-fusao").value==="screen","Escolher preto mantém a fusão clara selecionada");
  afirmar(pixel(100,80)[1]<30,"Preto marca detalhes visíveis sem sair da fusão clara");
  afirmar(pixel(115,98)[1]<pixel(100,80)[1],"Preto preserva diferenças de textura da imagem original");
  await ajustar("cor","#0a0622");await ajustar("colorir",55);await ajustar("brilho",233);
  afirmar($("modo-fusao").value==="screen" && pixel(100,80)[1]<30,"Cor e ajustes da captura do usuário mantêm Hycosy visível no modo escolhido");
  afirmar(pixel(78,73).join()==="20,40,60,255" && pixel(0,0).join()==="180,200,220,255","Mistura escura preserva transparência e cabeçalho");
  const escuroEsperado=pixels().slice(),pngEscuro=await new Promise(r=>canvas.toBlob(r));
  const urlEscuro=URL.createObjectURL(pngEscuro),imgEscura=new Image();imgEscura.src=urlEscuro;await imgEscura.decode();
  const cvEscuro=document.createElement("canvas");cvEscuro.width=200;cvEscuro.height=150;const cxEscuro=cvEscuro.getContext("2d");cxEscuro.drawImage(imgEscura,0,0);URL.revokeObjectURL(urlEscuro);
  afirmar(cxEscuro.getImageData(0,0,200,150).data.every((n,i)=>n===escuroEsperado[i]),"PNG preserva mistura escura e detalhes da prévia");
  await ajustar("colorir",100);await ajustar("cor","#000000");
  await modo("source-over");
  afirmar(pixel(100,80)[0]<20 && pixel(100,80)[1]<40,"Sobreposição normal escolhida manualmente permite preto");
  afirmar(pixel(78,73).join()==="20,40,60,255","Cor preta não altera a máscara transparente da Hycosy");
  await modo("screen");await ajustar("cor","#182040");
  afirmar($("modo-fusao").value==="screen","Escolher azul escuro mantém a fusão clara selecionada");
  await ajustar("colorir",40);
  afirmar($("modo-fusao").value==="screen","Alterar intensidade de cor escura não muda o modo de fusão");
  $("repor").click();await quadro();
  await ajustar("cor","#00ff00");
  afirmar($("colorir").value==="100","Escolher cor da Hycosy ativa o efeito automaticamente");
  await ajustar("contraste",130);await ajustar("brilho",160);
  afirmar(pixel(100,80)[1]>pixel(100,80)[0],"Cor, contraste e brilho aplicados à camada: "+pixel(100,80).join());
  await ajustar("cor-base","#0000ff");
  afirmar($("colorir-base").value==="100","Escolher cor do 3D ativa seu efeito independentemente");
  const baseAzul=pixel(0,80);
  afirmar(baseAzul[0]===0 && baseAzul[1]===0 && baseAzul[2]>0,"3D recebe a cor escolhida");
  afirmar($("cor").value==="#00ff00" && pixel(100,80)[1]>pixel(100,80)[0],"Cor da Hycosy permanece independente do 3D");
  afirmar(ctx.getImageData(0,0,200,18).data.every((n,i)=>n===[180,200,220,255][i%4]),"Cor do 3D preserva todos os pixels do cabeçalho");
  await ajustar("cabecalho",40);
  afirmar(pixel(0,40).join()==="20,40,60,255","Aumentar faixa protegida recupera os pixels originais do 3D");
  await ajustar("cabecalho",12);
  await ajustar("largura",120);await ajustar("altura",110);
  const composicaoEsperada=pixels().slice();
  $("comparar").checked=true;$("comparar").dispatchEvent(new w.Event("change"));await quadro();
  afirmar(pixel(100,80).join()==="20,40,60,255","Comparação mostra a base original");
  let blobExportado=null;
  const originalToBlob=canvas.toBlob.bind(canvas);
  canvas.toBlob=(cb,...args)=>originalToBlob(blob=>{blobExportado=blob;cb(blob);},...args);
  w.HTMLAnchorElement.prototype.click=function(){};
  $("baixar").click();await ate(()=>blobExportado && !$("baixar").disabled);
  const img=new Image(),url=URL.createObjectURL(blobExportado);img.src=url;await img.decode();
  const ec=document.createElement("canvas");ec.width=200;ec.height=150;const ex=ec.getContext("2d");ex.drawImage(img,0,0);URL.revokeObjectURL(url);
  afirmar(img.width===200 && img.height===150,"PNG mantém resolução original");
  afirmar(ex.getImageData(0,0,200,150).data.every((n,i)=>n===composicaoEsperada[i]),"PNG reproduz prévia com fusão clara, cor do 3D e proporções ajustadas");
  afirmar(Array.from(ex.getImageData(0,80,1,1).data).join()===baseAzul.join(),"PNG inclui a cor ajustada do 3D");
  afirmar(ex.getImageData(100,80,1,1).data[1]>40,"Download contém composição mesmo durante comparação");
  afirmar(ex.getImageData(0,0,200,18).data.every((n,i)=>n===[180,200,220,255][i%4]),"PNG preserva cabeçalho integralmente");
  afirmar(pixel(100,80).join()==="20,40,60,255","Exportação restaura a comparação na tela");
  let jpegExportado=null,nomeJpeg='',totalJpeg=0;
  const criarUrlJpeg=w.URL.createObjectURL.bind(w.URL);
  w.URL.createObjectURL=blob=>{if(blob.type==='image/jpeg'){jpegExportado=blob;totalJpeg++;}return criarUrlJpeg(blob);};
  w.HTMLAnchorElement.prototype.click=function(){nomeJpeg=this.download;};
  $('baixar-jpeg').click();$('baixar-jpeg').click();
  afirmar($('baixar').disabled && $('baixar-jpeg').disabled && $('baixar-pdf').disabled,'JPEG bloqueia downloads simultâneos');
  await ate(()=>jpegExportado && !$('baixar-jpeg').disabled);
  afirmar(totalJpeg===1 && nomeJpeg==='endomapa-fusao-hycosy.jpg','Um único JPEG com extensão correta');
  const bytesJpeg=new Uint8Array(await jpegExportado.arrayBuffer());
  afirmar(bytesJpeg[0]===255 && bytesJpeg[1]===216,'JPEG contém assinatura binária correta');
  const imgJpeg=new Image(),urlJpeg=URL.createObjectURL(jpegExportado);imgJpeg.src=urlJpeg;await imgJpeg.decode();
  afirmar(imgJpeg.width===200 && imgJpeg.height===150,'JPEG mantém resolução do 3D');
  ex.drawImage(imgJpeg,0,0);URL.revokeObjectURL(urlJpeg);
  const pixelsJpeg=ex.getImageData(0,0,200,150).data;
  const erroJpeg=pixelsJpeg.reduce((s,v,i)=>s+Math.abs(v-composicaoEsperada[i]),0)/pixelsJpeg.length;
  afirmar(erroJpeg<5,'JPEG preserva a composição com tolerância à compressão');
  afirmar(pixel(100,80).join()==='20,40,60,255','JPEG restaura comparação na tela');
  let pdfExportado=null,imagemPdf=null,chamadasPdf=0;
  const gerarPdf=w.hycosyGerarPdf;
  w.hycosyGerarPdf=c=>{chamadasPdf++;imagemPdf=c.getContext("2d").getImageData(0,0,200,150).data;pdfExportado=gerarPdf(c);return pdfExportado;};
  $("baixar-pdf").click();$("baixar-pdf").click();
  afirmar($("baixar").disabled && $("baixar-pdf").disabled,"Downloads bloqueados durante preparação do PDF");
  await ate(()=>pdfExportado && !$("baixar-pdf").disabled);
  afirmar(chamadasPdf===1,"Clique duplicado não gera dois PDFs simultâneos");
  afirmar(imagemPdf.every((n,i)=>n===composicaoEsperada[i]),"PDF recebe composição completa mesmo durante comparação com original");
  const textoPdf=new TextDecoder("latin1").decode(await pdfExportado.arrayBuffer());
  afirmar(pdfExportado.type==="application/pdf" && textoPdf.startsWith("%PDF-"),"Download é um arquivo PDF válido");
  afirmar(textoPdf.includes("/Width 200") && textoPdf.includes("/Height 150"),"PDF incorpora a imagem sem reduzir sua resolução");
  const caixa=textoPdf.match(/\/MediaBox\s*\[0 0 ([\d.]+) ([\d.]+)\]/);
  afirmar(caixa && Math.abs(Number(caixa[1])-841.89)<1 && Math.abs(Number(caixa[2])-595.28)<1,"PDF usa A4 deitado para imagem horizontal");
  afirmar(pixel(100,80).join()==="20,40,60,255","PDF preserva a comparação e a edição na tela");
  w.hycosyGerarPdf=()=>{throw new Error("Falha simulada");};$("baixar-pdf").click();await ate(()=>!$("baixar-pdf").disabled);
  afirmar($("estado").classList.contains("erro") && canvas.width===200,"Falha de PDF preserva montagem e libera nova tentativa");
  w.hycosyGerarPdf=gerarPdf;
  await ajustar("colorir-base",0);
  afirmar(!$("comparar").checked && pixel(0,80).join()==="20,40,60,255","Intensidade zero recupera cor original do 3D e exibe composição");
  $("comparar").checked=false;$("comparar").dispatchEvent(new w.Event("change"));
  $("contorno").click();
  function ponteiro(tipo,x,y){const c=$("origem"),r=c.getBoundingClientRect();c.dispatchEvent(new w.PointerEvent(tipo,{bubbles:true,pointerId:1,clientX:r.left+x/200*r.width,clientY:r.top+y/150*r.height,button:0}));}
  ponteiro("pointerdown",50,30);ponteiro("pointerdown",140,30);ponteiro("pointerdown",95,110);
  afirmar($("baixar").disabled,"Contorno inacabado bloqueia exportação");
  $("fechar").click();await quadro();afirmar(!$("baixar").disabled,"Contorno aplicado permite composição");
  inserir("base",new File(["invalido"],"arquivo.txt",{type:"text/plain"}));await esperar(100);
  afirmar($("estado").classList.contains("erro") && canvas.width===200,"Arquivo inválido não apaga a base anterior");
  await ajustar("cor-base","#ff0000");$("repor").click();await quadro();
  afirmar($("colorir-base").value==="0" && $("colorir").value==="0" && pixel(0,80).join()==="20,40,60,255","Restaurar ajustes recupera as duas cores originais");
  afirmar($("largura").value==="100" && $("altura").value==="100","Restaurar ajustes recupera proporções originais");
  await ajustar("x",62);await ajustar("escala",75);await ajustar("giro",12);await ajustar("rx",20);await ajustar("ry",-15);await ajustar("colorir",65);await modo("source-over");
  $("fusao-clara").click();await quadro();
  afirmar($("modo-fusao").value==="screen" && $("brilho").value==="180" && $("opacidade").value==="85" && $("colorir").value==="0","Ajuste de fusão clara aplica aparência inicial sem tingimento forçado");
  afirmar(Math.abs(Number($("x").value)-62)<.01 && $("escala").value==="75" && $("giro").value==="12" && $("rx").value==="20" && $("ry").value==="-15","Ajuste de fusão clara mantém posição por arraste, tamanho e angulações");
  for(const largura of [320,390,768,1280]){
    iframe.width=largura;await esperar(80);afirmar(d.documentElement.scrollWidth<=d.documentElement.clientWidth,"Sem rolagem horizontal em "+largura+"px");
    const previa=d.querySelector(".previa-fixa"),ferramentas=d.querySelector(".ferramentas");
    afirmar(w.getComputedStyle(previa).position==="sticky","Prévia acompanha ajustes em "+largura+"px");
    if(largura>=900)afirmar(ferramentas.getBoundingClientRect().left>=previa.getBoundingClientRect().right,"Ferramentas ao lado da imagem no computador");
  }
  w.confirm=()=>true;$("limpar").click();await quadro();
  afirmar($("baixar").disabled && !$("vazio-base").hidden,"Limpeza descarta montagem e bloqueia download");
  relatorio.textContent="PASSOU: "+logs.length+" verificações\n"+logs.join("\n");
 }catch(e){relatorio.textContent="FALHOU: "+e.message+"\n"+logs.join("\n");}
 if(location.hostname==="localhost")await fetch("/resultado-hycosy",{method:"POST",body:relatorio.textContent});
})();
